# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Fallout 3
    url: voci/fallout-3
    identifier: fallout3
    weight: 10
  - name: SPECIAL TODO
    parent: fallout3
    url:  
    weight: 10
  - name: Abilità TODO
    parent: fallout3
    url:  
    weight: 20
  - name: Abilità extra
    parent: fallout3
    url: voci/fallout-3/personaggio/abilita-extra 
    weight: 30
  - name: Companions TODO
    parent: fallout3
    url:  
    weight: 40
  - name: Mercanti TODO
    parent: fallout3
    url:  
    weight: 45
  - name: Creature e robot TODO
    parent: fallout3
    url:  
    weight: 50
  - name: Armi e munizioni TODO
    parent: fallout3
    url:  
    weight: 55
  - name: Armature e copricapi TODO
    parent: fallout3
    url:  
    weight: 60
  - name: Cibi, bevande e droghe TODO
    identifier: consumabili
    parent: fallout3
    url:  
    weight: 70
  - name: Luoghi 
    parent: fallout3
    url: voci/fallout-3/luoghi 
    weight: 9 
  - name: Missioni
    identifier: missioni
    parent: fallout3
    url: voci/fallout-3/missioni
    weight: 90
  - name: <b>Pagina principale</b>
    parent: fallout3
    url: voci/fallout-3
    weight: 8
  - name: Fallout New Vegas
    url: voci/fallout-new-vegas
    weight: 20    
