# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: 
  theme_night: custom
  font: cyberpunk
  font_size: m

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: ''
    description: 'Una guida di sopravvivenza alla Zona contaminata utile per ogni vagabondo solitario'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: 'L2vepQNNSnC-xwXbXpFm_SGhReXJWKQyM_NN044cY_s'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} persycchiotto. Questo sito utilizza la licenza {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Mon, 02 Jan 2006'
  time_format: '15:04'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false

  feedback:
    responses:
      positive: 'Ti è piaciuto, eh? [Hai in mente qualche miglioria?](https://github.com/persy/wastelander/issues/new).'
      negative: 'Mannaggia,  ci spiace.. [Dicci cosa non va](https://github.com/persy/wastelander/issues/new).'
  comment:
    provider: disqus
    disqus:
      shortname: wastelander
      show_count: true
    commento:
      url: ''
    giscus:
      repo: 'persy/wastelander'
      repo_id: 'R_kgDOIahcnw'
      category: ''
      category_id: 'DIC_kwDOIahcn84CSkFc'
      language_code: it
      mapping: pathname
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
